### ISSUE TITLE
QoS-Class-Identifier enum is missing some values in diameter_3gpp_ts32_299_rf

### ISSUE THREAD

**Issue by ebengt** [travelping/ergw_aaa#71]
DIAMETER encode crash when QoS-Class-Identifier is 255.

Dictionary diameter_3gpp_ts32_299_rf is missing some enum values from Rel15.

Either add missing enum values or change from enum ''type'' to allow any class code.

**Comment by vkatsuba** [comment]
Fixed in the scope of PR https://github.com/travelping/ergw_aaa/pull/88

**Comment by vkatsuba** [comment]
Closed. Fix provided, common tests updated, issue looks fixed. Please feel free to re-open if you will have any issues in further.
